### ISSUE TITLE
Add a way to clear Likes

### ISSUE THREAD

**Issue by JoarHansson** [JoarHansson/space-images-app#10]
Files:
- `src/services/utils.js`
- `src/pages/Likes/Likes.jsx`

Likes are saved in local storage. 
- Add a function that clears the local storage and removes all the saved likes. 
- Add a "clear likes"-button somewhere in `src/pages/Likes/Likes.jsx` that calls the function
  - Maybe with a prompt "are you sure?"

**Comment by shakilakamalasena** [comment]
I'd like to do it.

**Comment by JoarHansson** [comment]
Thank you!

**Comment by shakilakamalasena** [comment]
I've just opened a pull request for this feature. Would appreciate it if you could review it.

**Comment by JoarHansson** [comment]
Issue resolved in PR #12
