### ISSUE TITLE
Change component name from Home to Explore

### ISSUE THREAD

**Issue by JoarHansson** [JoarHansson/space-images-app#8]
## Change name from Home to Explore. 

**Reason**: This feels like a more suiting name for that part of the app.

**Clarification**: Everywhere in the app where something is referred to as "Home", it should instead be referred to as "Explore". This means css classes, component names etc should change. 

**Example**: 
- `src/pages/Home.jsx` should be changed to `src/pages/Explore.jsx`
- The exported component in above file should be changed from `Home()`to `Explore()`

### This is where you can find "Home" in the app that i can think of (There might be more places):

File/folder names that need to be changed:
- `src/pages/Home`
- `src/pages/Home/Home.jsx` + name of the exported component in the file, and css class names (see below)
- `src/pages/Home/Home.module.css` + class names including  "home"

Links/Routes/name of URLs that need to be changed:
- `src/pages/Index/Index.jsx`
- `src/components/Header/Header.jsx`
- `src/App.jsx`

**Comment by AviraLS22** [comment]
can you please clearify which files' name shold be changed and what should be the name ?

**Comment by JoarHansson** [comment]
> can you please clearify which files' name shold be changed and what should be the name ?

Hi! 

I updated the comment at the top of the issue with more clarification. Hope that helps!
